// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Blog struct {
	ID        uuid.UUID
	Author    uuid.UUID
	Content   string
	CreatedAt pgtype.Timestamp
}

type Follow struct {
	Follower uuid.UUID
	Followee uuid.UUID
}

type User struct {
	ID        uuid.UUID
	Username  string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamp
}
