// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Blog struct {
	ID        uuid.UUID
	Author    uuid.UUID
	Content   string
	CreatedAt time.Time
}

type Follow struct {
	Follower uuid.UUID
	Followee uuid.UUID
}

type User struct {
	ID        uuid.UUID
	Username  string
	Email     string
	Password  string
	CreatedAt time.Time
}
