// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Blog struct {
	ID        pgtype.UUID
	Author    pgtype.UUID
	Content   string
	CreatedAt pgtype.Timestamp
}

type Follow struct {
	Follower pgtype.UUID
	Followee pgtype.UUID
}

type User struct {
	ID        pgtype.UUID
	Username  string
	Email     string
	CreatedAt pgtype.Timestamp
}
