version: "3.9"

services:
  cache:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379

  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: blogapp
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
