name: Build Microservices
run-name: Building docker images from the microservices
on: [push]
jobs:
  Build-and-Push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - auth
          - follow
          - blogs
          - home-feed
          - search
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            DIR=${{ matrix.service }}
          tags: |
            kylethenewbie/blogapp-${{ matrix.service }}:latest
